# Generated by Django 3.1.6 on 2021-02-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20210215_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='price',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
