# Generated by Django 3.1.6 on 2021-02-22 08:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_auto_20210219_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='pub_date',
            field=models.DateField(default=datetime.date(2021, 2, 22)),
        ),
    ]
