# Generated by Django 3.1.6 on 2021-02-22 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_auto_20210222_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='pub_date',
            field=models.DateField(),
        ),
    ]
