# Generated by Django 3.1.6 on 2021-02-22 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_auto_20210222_0857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phone',
            new_name='sellerTlf',
        ),
    ]
