<<<<<<< HEAD
# Generated by Django 3.1.6 on 2021-03-22 13:57
=======
# Generated by Django 3.1.6 on 2021-03-15 10:52
>>>>>>> 974816a0be9cc1f88079d10734e5775d9269f9a3

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('auth', '0012_alter_user_first_name_max_length'),
=======
        ("auth", "0012_alter_user_first_name_max_length"),
>>>>>>> 974816a0be9cc1f88079d10734e5775d9269f9a3
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('phone', models.CharField(max_length=80)),
                ('city', models.CharField(max_length=50)),
                ('birth_year', models.CharField(max_length=20)),
=======
            name="Profile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to="auth.user"
                    ),
                ),
                ("phone", models.CharField(max_length=80)),
                ("city", models.CharField(max_length=50)),
                ("birth_year", models.CharField(max_length=20)),
>>>>>>> 974816a0be9cc1f88079d10734e5775d9269f9a3
            ],
        ),
    ]
