# Generated by Django 3.1.6 on 2021-03-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ad",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("pub_date", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("price", models.PositiveIntegerField()),
                ("img", models.ImageField(upload_to="product/")),
                ("category", models.CharField(max_length=50)),
                ("city", models.CharField(default="Ikke oppgitt", max_length=100)),
            ],
        ),
    ]
