<<<<<<< HEAD
# Generated by Django 3.1.6 on 2021-03-22 13:57
=======
# Generated by Django 3.1.6 on 2021-03-15 10:52
>>>>>>> 974816a0be9cc1f88079d10734e5775d9269f9a3

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

<<<<<<< HEAD
    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category', models.CharField(max_length=40, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('img', models.ImageField(upload_to='product/')),
                ('city', models.CharField(default='Ikke oppgitt', max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad.category')),
=======
    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("category", models.CharField(max_length=40, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name="Ad",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("pub_date", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("price", models.PositiveIntegerField()),
                ("img", models.ImageField(upload_to="product/")),
                ("city", models.CharField(default="Ikke oppgitt", max_length=100)),
                ("category", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="ad.category")),
>>>>>>> 974816a0be9cc1f88079d10734e5775d9269f9a3
            ],
        ),
    ]
