# Generated by Django 3.1.6 on 2021-04-07 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ad", "0001_initial"),
        ("rating", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ad",
            name="rating",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="rating.rating"),
        ),
        migrations.AlterUniqueTogether(
            name="favorite",
            unique_together={("profile", "ad")},
        ),
    ]
