<<<<<<< HEAD
# Generated by Django 3.1.6 on 2021-03-22 13:57
=======
# Generated by Django 3.1.6 on 2021-03-15 10:52
>>>>>>> 974816a0be9cc1f88079d10734e5775d9269f9a3

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('ad', '0001_initial'),
        ('user', '0001_initial'),
=======
        ("user", "0001_initial"),
        ("ad", "0001_initial"),
>>>>>>> 974816a0be9cc1f88079d10734e5775d9269f9a3
    ]

    operations = [
        migrations.AddField(
<<<<<<< HEAD
            model_name='ad',
            name='created_by_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile'),
=======
            model_name="ad",
            name="created_by_user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="user.profile"),
>>>>>>> 974816a0be9cc1f88079d10734e5775d9269f9a3
        ),
    ]
