# Generated by Django 3.1.6 on 2021-02-19 07:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0004_ad_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(upload_to='upload/'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='pub_date',
            field=models.DateField(default=datetime.date(2021, 2, 19)),
        ),
    ]
