# Generated by Django 3.1.6 on 2021-02-22 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ad', '0007_auto_20210222_0827'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('phone', models.CharField(max_length=80)),
                ('city', models.CharField(max_length=50)),
                ('birth_year', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='ad',
            old_name='image',
            new_name='imgUrl',
        ),
        migrations.RenameField(
            model_name='ad',
            old_name='headline',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='ad',
            name='created_by_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad.profile'),
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
