# Generated by Django 3.1.6 on 2021-02-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0009_auto_20210222_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='imgUrl',
            field=models.ImageField(upload_to='ads/'),
        ),
    ]
